title: Ruffle
# email: mwelsh@gmail.com
description: >- 
  使用 Rust 语言编写的 Flash Player 模拟器
baseurl: ""
#url: "https://ruffle.rs"
# twitter_username: jekyllrb
github_username:  ruffle-rs
github_url: "https://github.com/imgradeone/ruffle-website-cn"
repository: ruffle-rs/ruffle
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-seo-tag
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docker-compose.yml
